version: "3.9"
networks:
  database_db_one:
    external: true
    name: database_db_one
  lr_project_two:
services:
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - redis
      - mysql
      - lr_project_two
    container_name: lr_project_two_server
    networks:
      - lr_project_two
      - database_db_one
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: php_lr_project_two_server
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - 8088:9000
    networks:
      - lr_project_two
      - database_db_one
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - lr_project_two
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - lr_project_two
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - lr_project_two
