version: "3.9"
networks:
  # jhe_sso_one:
    # external: true
    # name: jhe_sso_one
  lr_project:
services:
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - redis
      - mysql
      # - jhe_sso_one
      - lr_project
    container_name: lr_project_server
    networks:
      - lr_project
      # - jhe_sso_one
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: php_lr_project_server
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - 8088:9000
    networks:
      - lr_project
      # - jhe_sso_one
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - lr_project
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - lr_project
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - lr_project
  mysql:
    image: mysql:8.0.1
    restart: unless-stopped
    tty: true
    container_name: mysql_lr_project
    env_file:
      - ./mysql/mysql.env
    ports:
      - 3306:3306
    networks:
      - lr_project
    volumes:
      - /opt/mysql_data_sso_one:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin_lr_project
    depends_on:
      - mysql
    ports:
      - '8890:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    networks:
      - lr_project
